simple-1:
  description: "This is repo-1"
  topics: ["repository-topic"]

simple-2:
  description: "This is repo-2"
  issue_labels:
    Urgent: "This is an urgent issue"
    Critical: "This is a critical issue"
  autolink_references:
    ID-: "https://www.mycompany.com/issues/<num>"
  files:
    - file: TEST-README.md
      from_file: ../../README.md
  #custom_properties:
  #  test-property: "value-3"
  enable_actions: false
  variables:
    MYVAR: "myvalue"

simple-6:
  alias: test-suborg-simple-3
  description: "This is repo-3"
  homepage: "https://www.mycompany.com/issues/"
  topics: ["topic-1", "topic-2"]
  enable_vulnerability_alerts: true
  # pages:
  #   source:
  #     branch: master
  #     path: /docs
  #   build_type: legacy
  # collaborators:
  #   teams:
  #     someteam: pull
  deploy_keys:
    demo: true
