visibility: public

# issue_labels:
#   Settings:
#     color: "00ff00"
#     description: "This is a fixed issue"


autolink_references:
  JIRA-:
    target_url_template: "https://jira.mycompany.com/issues/<num>"

homepage_url: "https://www.google.com"

topics: ["settings-a", "settings-b"]
